ALTER TABLE REGION MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE  REGION SET ID = ID + 10000000000000;
ALTER TABLE REGION AUTO_INCREMENT = 1;

ALTER TABLE EQUIPMENT_HOLDER MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT; 
UPDATE EQUIPMENT_HOLDER SET ID = ID + 10000000000000;
ALTER TABLE EQUIPMENT_HOLDER MODIFY OBJECT_ID BIGINT UNSIGNED;
UPDATE EQUIPMENT_HOLDER SET OBJECT_ID = OBJECT_ID + 10000000000000;
ALTER TABLE EQUIPMENT_HOLDER AUTO_INCREMENT = 1;

ALTER TABLE REVIEWER MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE REVIEWER SET ID = ID + 10000000000000;
ALTER TABLE REVIEWER MODIFY OBJECT_ID BIGINT UNSIGNED;
UPDATE REVIEWER SET OBJECT_ID = OBJECT_ID + 10000000000000;
ALTER TABLE REVIEWER AUTO_INCREMENT = 1;

ALTER TABLE DEVELOPMENT_MANAGER MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE DEVELOPMENT_MANAGER SET ID = ID + 10000000000000;
ALTER TABLE DEVELOPMENT_MANAGER MODIFY REGION_ID BIGINT UNSIGNED;
UPDATE DEVELOPMENT_MANAGER SET REGION_ID = REGION_ID + 10000000000000;
ALTER TABLE DEVELOPMENT_MANAGER AUTO_INCREMENT = 1;

ALTER TABLE STATE MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE STATE SET ID = ID + 10000000000000;
ALTER TABLE STATE MODIFY REGION_ID BIGINT UNSIGNED;
UPDATE STATE SET REGION_ID = REGION_ID + 10000000000000;
ALTER TABLE STATE AUTO_INCREMENT = 1;

ALTER TABLE PARTNERS MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE PARTNERS SET ID = ID + 10000000000000;
ALTER TABLE PARTNERS AUTO_INCREMENT = 1;

ALTER TABLE FIELD_OFFICER MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE FIELD_OFFICER SET ID = ID + 10000000000000;
ALTER TABLE FIELD_OFFICER AUTO_INCREMENT = 1;

ALTER TABLE DISTRICT MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE DISTRICT SET ID = ID + 10000000000000;
ALTER TABLE DISTRICT MODIFY STATE_ID BIGINT UNSIGNED;
UPDATE DISTRICT SET STATE_ID = STATE_ID + 10000000000000;
ALTER TABLE DISTRICT MODIFY FIELDOFFICER_ID BIGINT UNSIGNED;
UPDATE DISTRICT SET FIELDOFFICER_ID = FIELDOFFICER_ID + 10000000000000;
ALTER TABLE DISTRICT MODIFY PARTNER_ID BIGINT UNSIGNED;
UPDATE DISTRICT SET PARTNER_ID = PARTNER_ID + 10000000000000;
ALTER TABLE DISTRICT AUTO_INCREMENT = 1;

ALTER TABLE BLOCK MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE BLOCK SET ID = ID + 10000000000000;
ALTER TABLE BLOCK MODIFY DISTRICT_ID BIGINT UNSIGNED;
UPDATE BLOCK SET DISTRICT_ID = DISTRICT_ID + 10000000000000;
ALTER TABLE BLOCK AUTO_INCREMENT = 1;

ALTER TABLE VILLAGE MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE VILLAGE SET ID = ID + 10000000000000;
ALTER TABLE VILLAGE MODIFY BLOCK_ID BIGINT UNSIGNED;
UPDATE VILLAGE SET BLOCK_ID = BLOCK_ID + 10000000000000;
ALTER TABLE VILLAGE AUTO_INCREMENT = 1;

ALTER TABLE MONTHLY_COST_PER_VILLAGE MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE MONTHLY_COST_PER_VILLAGE SET ID = ID + 10000000000000;
ALTER TABLE MONTHLY_COST_PER_VILLAGE MODIFY VILLAGE_ID BIGINT UNSIGNED;
UPDATE MONTHLY_COST_PER_VILLAGE SET VILLAGE_ID = VILLAGE_ID + 10000000000000;
ALTER TABLE MONTHLY_COST_PER_VILLAGE AUTO_INCREMENT = 1;

ALTER TABLE PERSON_GROUPS MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE PERSON_GROUPS SET ID = ID + 10000000000000;
ALTER TABLE PERSON_GROUPS MODIFY VILLAGE_ID BIGINT UNSIGNED;
UPDATE PERSON_GROUPS SET VILLAGE_ID = VILLAGE_ID + 10000000000000;
ALTER TABLE PERSON_GROUPS AUTO_INCREMENT = 1;

ALTER TABLE PERSON MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE PERSON SET ID = ID + 10000000000000;
ALTER TABLE PERSON MODIFY VILLAGE_ID BIGINT UNSIGNED;
UPDATE PERSON SET VILLAGE_ID = VILLAGE_ID + 10000000000000;
ALTER TABLE PERSON MODIFY GROUP_ID BIGINT UNSIGNED;
UPDATE PERSON SET GROUP_ID = GROUP_ID + 10000000000000;
ALTER TABLE PERSON AUTO_INCREMENT = 1;

ALTER TABLE PERSON_RELATIONS MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE PERSON_RELATIONS SET ID = ID + 10000000000000;
ALTER TABLE PERSON_RELATIONS MODIFY PERSON_ID BIGINT UNSIGNED;
UPDATE PERSON_RELATIONS SET PERSON_ID = PERSON_ID + 10000000000000;
ALTER TABLE PERSON_RELATIONS MODIFY RELATIVE_ID BIGINT UNSIGNED;
UPDATE PERSON_RELATIONS SET RELATIVE_ID = RELATIVE_ID + 10000000000000;
ALTER TABLE PERSON_RELATIONS AUTO_INCREMENT = 1;

ALTER TABLE ANIMATOR MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE ANIMATOR SET ID = ID + 10000000000000;
ALTER TABLE ANIMATOR MODIFY PARTNER_ID BIGINT UNSIGNED;
UPDATE ANIMATOR SET PARTNER_ID = PARTNER_ID + 10000000000000;
ALTER TABLE ANIMATOR MODIFY HOME_VILLAGE_ID BIGINT UNSIGNED;
UPDATE ANIMATOR SET HOME_VILLAGE_ID = HOME_VILLAGE_ID + 10000000000000;
ALTER TABLE ANIMATOR AUTO_INCREMENT = 1;

ALTER TABLE TRAINING MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE TRAINING SET ID = ID + 10000000000000;
ALTER TABLE TRAINING MODIFY VILLAGE_ID BIGINT UNSIGNED;
UPDATE TRAINING SET VILLAGE_ID = VILLAGE_ID + 10000000000000;
ALTER TABLE TRAINING MODIFY DM_ID BIGINT UNSIGNED;
UPDATE TRAINING SET DM_ID = DM_ID + 10000000000000;
ALTER TABLE TRAINING MODIFY FIELDOFFICER_ID BIGINT UNSIGNED;
UPDATE TRAINING SET FIELDOFFICER_ID = FIELDOFFICER_ID + 10000000000000;
ALTER TABLE TRAINING AUTO_INCREMENT = 1;

ALTER TABLE TRAINING_animators_trained MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE TRAINING_animators_trained SET ID = ID + 10000000000000;
ALTER TABLE TRAINING_animators_trained MODIFY TRAINING_ID BIGINT UNSIGNED;
UPDATE TRAINING_animators_trained SET TRAINING_ID = TRAINING_ID + 10000000000000;
ALTER TABLE TRAINING_animators_trained MODIFY ANIMATOR_ID BIGINT UNSIGNED;
UPDATE TRAINING_animators_trained SET ANIMATOR_ID = ANIMATOR_ID + 10000000000000;
ALTER TABLE TRAINING_animators_trained AUTO_INCREMENT = 1;

ALTER TABLE ANIMATOR_ASSIGNED_VILLAGE MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE ANIMATOR_ASSIGNED_VILLAGE SET ID = ID + 10000000000000;
ALTER TABLE ANIMATOR_ASSIGNED_VILLAGE MODIFY ANIMATOR_ID BIGINT UNSIGNED;
UPDATE ANIMATOR_ASSIGNED_VILLAGE SET ANIMATOR_ID = ANIMATOR_ID + 10000000000000;
ALTER TABLE ANIMATOR_ASSIGNED_VILLAGE MODIFY VILLAGE_ID BIGINT UNSIGNED;
UPDATE ANIMATOR_ASSIGNED_VILLAGE SET VILLAGE_ID = VILLAGE_ID + 10000000000000;
ALTER TABLE ANIMATOR_ASSIGNED_VILLAGE AUTO_INCREMENT = 1;

ALTER TABLE ANIMATOR_SALARY_PER_MONTH MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE ANIMATOR_SALARY_PER_MONTH SET ID = ID + 10000000000000;
ALTER TABLE ANIMATOR_SALARY_PER_MONTH MODIFY ANIMATOR_ID BIGINT UNSIGNED;
UPDATE ANIMATOR_SALARY_PER_MONTH SET ANIMATOR_ID = ANIMATOR_ID + 10000000000000;
ALTER TABLE ANIMATOR_SALARY_PER_MONTH AUTO_INCREMENT = 1;

ALTER TABLE LANGUAGE MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE LANGUAGE SET ID = ID + 10000000000000;
ALTER TABLE LANGUAGE AUTO_INCREMENT = 1;

ALTER TABLE PRACTICES MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE PRACTICES SET ID = ID + 10000000000000;
ALTER TABLE PRACTICES AUTO_INCREMENT = 1;

ALTER TABLE VIDEO MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE VIDEO SET ID = ID + 10000000000000;
ALTER TABLE VIDEO MODIFY LANGUAGE_ID BIGINT UNSIGNED;
UPDATE VIDEO SET LANGUAGE_ID = LANGUAGE_ID + 10000000000000;
ALTER TABLE VIDEO MODIFY VILLAGE_ID BIGINT UNSIGNED;
UPDATE VIDEO SET VILLAGE_ID = VILLAGE_ID + 10000000000000;
ALTER TABLE VIDEO MODIFY FACILITATOR_ID BIGINT UNSIGNED;
UPDATE VIDEO SET FACILITATOR_ID = FACILITATOR_ID + 10000000000000;
ALTER TABLE VIDEO MODIFY CAMERAOPERATOR_ID BIGINT UNSIGNED;
UPDATE VIDEO SET CAMERAOPERATOR_ID = CAMERAOPERATOR_ID + 10000000000000;
ALTER TABLE VIDEO MODIFY REVIEWER_ID BIGINT UNSIGNED;
UPDATE VIDEO SET REVIEWER_ID = REVIEWER_ID + 10000000000000;
ALTER TABLE VIDEO MODIFY SUPPLEMENTARY_VIDEO_PRODUCED_ID BIGINT UNSIGNED;
UPDATE VIDEO SET SUPPLEMENTARY_VIDEO_PRODUCED_ID = SUPPLEMENTARY_VIDEO_PRODUCED_ID + 10000000000000;
ALTER TABLE VIDEO AUTO_INCREMENT = 1;

ALTER TABLE VIDEO_related_agricultural_practices MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE VIDEO_related_agricultural_practices SET ID = ID + 10000000000000;
ALTER TABLE VIDEO_related_agricultural_practices MODIFY VIDEO_ID BIGINT UNSIGNED;
UPDATE VIDEO_related_agricultural_practices SET VIDEO_ID = VIDEO_ID + 10000000000000;
ALTER TABLE VIDEO_related_agricultural_practices MODIFY PRACTICES_ID BIGINT UNSIGNED;
UPDATE VIDEO_related_agricultural_practices SET PRACTICES_ID = PRACTICES_ID + 10000000000000;
ALTER TABLE VIDEO_related_agricultural_practices AUTO_INCREMENT = 1;

ALTER TABLE VIDEO_farmers_shown MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE VIDEO_farmers_shown SET ID = ID + 10000000000000;
ALTER TABLE VIDEO_farmers_shown MODIFY VIDEO_ID BIGINT UNSIGNED;
UPDATE VIDEO_farmers_shown SET VIDEO_ID = VIDEO_ID + 10000000000000;
ALTER TABLE VIDEO_farmers_shown MODIFY PERSON_ID BIGINT UNSIGNED;
UPDATE VIDEO_farmers_shown SET PERSON_ID = PERSON_ID + 10000000000000;
ALTER TABLE VIDEO_farmers_shown AUTO_INCREMENT = 1;

ALTER TABLE SCREENING MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE SCREENING SET ID = ID + 10000000000000;
ALTER TABLE SCREENING MODIFY VILLAGE_ID BIGINT UNSIGNED;
UPDATE SCREENING SET VILLAGE_ID = VILLAGE_ID + 10000000000000;
ALTER TABLE SCREENING MODIFY FIELDOFFICER_ID BIGINT UNSIGNED;
UPDATE SCREENING SET FIELDOFFICER_ID = FIELDOFFICER_ID + 10000000000000;
ALTER TABLE SCREENING MODIFY ANIMATOR_ID BIGINT UNSIGNED;
UPDATE SCREENING SET ANIMATOR_ID = ANIMATOR_ID + 10000000000000;
ALTER TABLE SCREENING AUTO_INCREMENT = 1;

ALTER TABLE SCREENING_farmer_groups_targeted MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE SCREENING_farmer_groups_targeted SET ID = ID + 10000000000000;
ALTER TABLE SCREENING_farmer_groups_targeted MODIFY SCREENING_ID BIGINT UNSIGNED;
UPDATE SCREENING_farmer_groups_targeted SET SCREENING_ID = SCREENING_ID + 10000000000000;
ALTER TABLE SCREENING_farmer_groups_targeted MODIFY PERSONGROUPS_ID BIGINT UNSIGNED;
UPDATE SCREENING_farmer_groups_targeted SET PERSONGROUPS_ID = PERSONGROUPS_ID + 10000000000000;
ALTER TABLE SCREENING_farmer_groups_targeted AUTO_INCREMENT = 1;

ALTER TABLE SCREENING_videoes_screened MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE SCREENING_videoes_screened SET ID = ID + 10000000000000;
ALTER TABLE SCREENING_videoes_screened MODIFY SCREENING_ID BIGINT UNSIGNED;
UPDATE SCREENING_videoes_screened SET SCREENING_ID = SCREENING_ID + 10000000000000;
ALTER TABLE SCREENING_videoes_screened MODIFY VIDEO_ID BIGINT UNSIGNED;
UPDATE SCREENING_videoes_screened SET VIDEO_ID = VIDEO_ID + 10000000000000;
ALTER TABLE SCREENING_videoes_screened AUTO_INCREMENT = 1;

ALTER TABLE PERSON_MEETING_ATTENDANCE MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE PERSON_MEETING_ATTENDANCE SET ID = ID + 10000000000000;
ALTER TABLE PERSON_MEETING_ATTENDANCE MODIFY SCREENING_ID BIGINT UNSIGNED;
UPDATE PERSON_MEETING_ATTENDANCE SET SCREENING_ID = SCREENING_ID + 10000000000000;
ALTER TABLE PERSON_MEETING_ATTENDANCE MODIFY PERSON_ID BIGINT UNSIGNED;
UPDATE PERSON_MEETING_ATTENDANCE SET PERSON_ID = PERSON_ID + 10000000000000;
ALTER TABLE PERSON_MEETING_ATTENDANCE MODIFY EXPRESSED_INTEREST_PRACTICE_ID BIGINT UNSIGNED;
UPDATE PERSON_MEETING_ATTENDANCE SET EXPRESSED_INTEREST_PRACTICE_ID = EXPRESSED_INTEREST_PRACTICE_ID + 10000000000000;
ALTER TABLE PERSON_MEETING_ATTENDANCE MODIFY EXPRESSED_ADOPTION_PRACTICE_ID BIGINT UNSIGNED;
UPDATE PERSON_MEETING_ATTENDANCE SET EXPRESSED_ADOPTION_PRACTICE_ID = EXPRESSED_ADOPTION_PRACTICE_ID + 10000000000000;
ALTER TABLE PERSON_MEETING_ATTENDANCE MODIFY EXPRESSED_QUESTION_PRACTICE_ID BIGINT UNSIGNED;
UPDATE PERSON_MEETING_ATTENDANCE SET EXPRESSED_QUESTION_PRACTICE_ID = EXPRESSED_QUESTION_PRACTICE_ID + 10000000000000;
ALTER TABLE PERSON_MEETING_ATTENDANCE AUTO_INCREMENT = 1;

ALTER TABLE PERSON_ADOPT_PRACTICE MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE PERSON_ADOPT_PRACTICE SET ID = ID + 10000000000000;
ALTER TABLE PERSON_ADOPT_PRACTICE MODIFY PERSON_ID BIGINT UNSIGNED;
UPDATE PERSON_ADOPT_PRACTICE SET PERSON_ID = PERSON_ID + 10000000000000;
ALTER TABLE PERSON_ADOPT_PRACTICE MODIFY PRACTICE_ID BIGINT UNSIGNED;
UPDATE PERSON_ADOPT_PRACTICE SET PRACTICE_ID = PRACTICE_ID + 10000000000000;
ALTER TABLE PERSON_ADOPT_PRACTICE AUTO_INCREMENT = 1;

ALTER TABLE EQUIPMENT_ID MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT ;
UPDATE EQUIPMENT_ID SET ID = ID + 10000000000000;
ALTER TABLE EQUIPMENT_ID MODIFY VILLAGE_ID BIGINT UNSIGNED;
UPDATE EQUIPMENT_ID SET VILLAGE_ID = VILLAGE_ID + 10000000000000;
ALTER TABLE EQUIPMENT_ID MODIFY EQUIPMENTHOLDER_ID BIGINT UNSIGNED;
UPDATE EQUIPMENT_ID SET EQUIPMENTHOLDER_ID = EQUIPMENTHOLDER_ID + 10000000000000;
ALTER TABLE EQUIPMENT_ID AUTO_INCREMENT = 1;

ALTER TABLE dashboard_userpermission MODIFY REGION_OPERATED_ID BIGINT UNSIGNED;
UPDATE dashboard_userpermission SET REGION_OPERATED_ID = REGION_OPERATED_ID + 10000000000000;
ALTER TABLE dashboard_userpermission MODIFY DISTRICT_OPERATED_ID BIGINT UNSIGNED;
UPDATE dashboard_userpermission SET DISTRICT_OPERATED_ID = DISTRICT_OPERATED_ID + 10000000000000;
ALTER TABLE dashboard_userpermission AUTO_INCREMENT = 1;

ALTER TABLE dashboard_target MODIFY ID BIGINT UNSIGNED AUTO_INCREMENT;
UPDATE dashboard_target SET ID = ID + 10000000000000;
ALTER TABLE dashboard_target MODIFY DISTRICT_ID BIGINT UNSIGNED;
UPDATE dashboard_target SET DISTRICT_ID = DISTRICT_ID + 10000000000000;
ALTER TABLE dashboard_target AUTO_INCREMENT = 1;

ALTER TABLE dashboard_error MODIFY district_id BIGINT UNSIGNED;
ALTER TABLE dashboard_error MODIFY object_id1 BIGINT UNSIGNED;
ALTER TABLE dashboard_error MODIFY object_id2 BIGINT UNSIGNED;