HEADER_STRING = "&CLoop India Bihar"
FOOTER_STRING = "&CThis is an automated generated sheet"
DEFAULT_COLUMN_WIDTH = 9

header_dict = {'headers': [{'aggregator':{'columns': [ {
                                                    'label': 'S No',
                                                    'formula': None,
                                                    'total': False,
                                                    'coloumn_width': 15,
                                                    },
                                                    {
                                                     'label': 'Date',
                                                     'total': False, 
                                                     'formula': None,
                                                     'coloumn_width': 3,
                                                    },
                                                    {
                                                     'label': 'Market',
                                                     'total': False, 
                                                     'formula': None,
                                                     'coloumn_width': 7,
                                                    },
                                                    {
                                                     'label': 'Quantity [Q] (in Kg)',
                                                     'total': True, 
                                                     'formula': None,
                                                     'coloumn_width': 6,
                                                    },

                                                    {'label': 'Aggregator Payment [AP] (in Rs) (0.25*Q)',
                                                     'total': True,
                                                     'formula': '0.25 * D',
                                                     'coloumn_width': 8.5,
                                                    },
                                                    {'label': 'Transport Cost [TC] (in Rs)',
                                                     'total': True,
                                                     'formula': None,
                                                     'coloumn_width': None,
                                                     
                                                    },
                                                    {'label': 'Farmers\''' Contribution [FC] (in Rs)',
                                                     'total': True,
                                                     'formula': None,
                                                     'coloumn_width': None,
                                                     
                                                    },
                                                    {'label': 'Commission Agent Contribution [CAC] (in Rs)',
                                                     'total': True,
                                                     'formula': None,
                                                     'coloumn_width': None,
                                                    },
                                                    {'label': 'Total Payment (in Rs) (AP + TC - FC - CAC)',
                                                     'total': True,
                                                     'formula': 'E + F - G - H',
                                                     'coloumn_width': None,
                                                    }],
                                            'data': [[], []]
                                            }},

                        {'gaddidar':{'columns': [ {'label': 'Date',
                                                'total': False, 
                                                'formula': None,
                                                'coloumn_width': None,
                                                },
                                                {'label': 'Commission Agent',
                                                 'total': False, 
                                                 'formula': None,
                                                 'coloumn_width': None,
                                                },
                                                { 'label': 'Market',
                                                  'total': False,  
                                                  'formula': None,
                                                  'coloumn_width': None,
                                                },
                                                {'label': 'Quantity [Q] (in Kg)',
                                                 'total': True,
                                                 'formula': None,
                                                 'coloumn_width': None,
                                                },
                                                {'label': 'Commission Agent Discount[CAD] (in Rs/Kg)',
                                                 'total': False, 
                                                 'formula': None,
                                                 'coloumn_width': None,
                                                },
                                                {'label': 'Commission Agent Contribution[CAC] (in Rs) (Q*CAD)',
                                                 'total': True,
                                                 'formula': 'D * E',
                                                 'coloumn_width': None,
                                                }],
                                   'data': [[], []]
                                    }
                        },
                        {'transporter':{'columns': [ {'label': 'Date',
                                                'total': False, 
                                                'formula': None,
                                                'coloumn_width': None,
                                                },
                                                {'label': 'Market',
                                                 'total': False, 
                                                 'formula': None,
                                                 'coloumn_width': None,
                                                },
                                                {'label': 'Transporter',
                                                 'total': False, 
                                                 'formula': None,
                                                 'coloumn_width': None,
                                                },
                                                {'label': 'Vehicle Type',
                                                 'total': False,
                                                 'formula': None,
                                                 'coloumn_width': None,
                                                },
                                                {'label': 'Vehicle Number',
                                                 'total': False, 
                                                 'formula': None,
                                                 'coloumn_width': None,
                                                },
                                                {'label': 'Tranport Cost (in Rs)',
                                                 'total': True,
                                                 'formula': None,
                                                 'coloumn_width': None,
                                                }],
                                   'data': [[], []]
                                    }
                        }],

}



