HEADER_STRING = "&CLoop India Bihar"
FOOTER_STRING = "&CThis is an automated generated sheet"
DEFAULT_COLUMN_WIDTH = 9

header_dict = {'aggregator':[{'coloumn_width': 15,
                                          'formula': None,
                                          'label': 'S No',
                                          'total': False},
                                         {'coloumn_width': None,
                                          'formula': None,
                                          'label': 'Date',
                                          'total': False},
                                         {'coloumn_width': None,
                                         'formula': None,
                                         'label': 'Market',
                                         'total': False},
                                         {'coloumn_width': None,
                                          'formula': None,
                                          'label': 'Quantity [Q] (in Kg)',
                                          'total': True},
                                         {'coloumn_width': None,
                                          'formula': '0.25 * D',
                                          'label': 'Aggregator Payment [AP] (in Rs) (0.25*Q)',
                                          'total': True},
                                         {'coloumn_width': None,
                                          'formula': None,
                                          'label': 'Transport Cost [TC] (in Rs)',
                                          'total': True},
                                         {'coloumn_width': None,
                                          'formula': None,
                                          'label': "Farmers' Contribution [FC] (in Rs)",
                                          'total': True},
                                         {'coloumn_width': None,
                                          'formula': None,
                                          'label': 'Commission Agent Contribution [CAC] (in Rs)',
                                          'total': True},
                                         {'coloumn_width': None,
                                          'formula': 'E + F - G - H',
                                          'label': 'Total Payment (in Rs) (AP + TC - FC - CAC)',
                                          'total': True}],
              'gaddidar': [{'coloumn_width': None,
                                          'formula': None,
                                          'label': 'Date',
                                          'total': False},
                                         {'coloumn_width': None,
                                          'formula': None,
                                          'label': 'Commission Agent',
                                          'total': False},
                                         {'coloumn_width': None,
                                          'formula': None,
                                          'label': 'Market',
                                          'total': False},
                                         {'coloumn_width': None,
                                          'formula': None,
                                          'label': 'Quantity [Q] (in Kg)',
                                          'total': True},
                                         {'coloumn_width': None,
                                          'formula': None,
                                          'label': 'Commission Agent Discount[CAD] (in Rs/Kg)',
                                          'total': False},
                                         {'coloumn_width': None,
                                          'formula': 'D * E',
                                          'label': 'Commission Agent Contribution[CAC] (in Rs) (Q*CAD)',
                                          'total': True}],
              'transporter': [{'coloumn_width': None,
                                          'formula': None,
                                          'label': 'Date',
                                          'total': False},
                                         {'coloumn_width': None,
                                          'formula': None,
                                          'label': 'Market',
                                          'total': False},
                                         {'coloumn_width': None,
                                          'formula': None,
                                          'label': 'Transporter',
                                          'total': False},
                                         {'coloumn_width': None,
                                          'formula': None,
                                          'label': 'Vehicle Type',
                                          'total': False},
                                         {'coloumn_width': None,
                                          'formula': None,
                                          'label': 'Vehicle Number',
                                          'total': False},
                                         {'coloumn_width': None,
                                          'formula': None,
                                          'label': 'Tranport Cost (in Rs)',
                                          'total': True}]
            }

