__author__ = 'Lokesh'

tableDictionary={
    'partner':'programs_partner',
    'country':'geographies_country',
    'state':'geographies_state',
    'district':'geographies_district',
    'block':'geographies_block',
    'village':'geographies_village',
    'animator':'people_animatorwisedata',
    'person':'people_person',
    'persongroup':'people_persongroup',
    'video':'videos_video_wisedata',
    'language':'videos_language',
    'sector':'videos_practicesector',
    'practice':'videos_practice',
    'topic':'videos_practicetopic',
    'numScreening':'activities_screeningwisedata',
    'numAdoption':'activities_personadoptpractice',
    'attendance':'activities_pmawisedata',
    'numPeople':'people_person',
    'numAnimator':'people_animatorwisedata',
    'listPeople':'people_person',
    'listAnimator':'people_animatorwisedata',
    'listVideoScreened':'activities_screeningwisedata',
    'numVideoScreened':'activities_screeningwisedata',
    'listVideoProduced':'videos_video_wisedata',
    'numVideoProduced':'videos_video_wisedata',
    'list':'self',
    'listGroup':'people_persongroup'
}

whereDictionary={
    'partner':'id',
    'country':'id',
    'state':'id',
    'district':'id',
    'block':'id',
    'village':'id',
    'animator':'animator_id',
    'person':'id',
    'persongroup':'id',
    'video':'id',
    'language':'id',
    'sector':'id',
    'practice':'id',
    'topic':'id',
    'numScreening':'screening_date',
    'numAdoption':'date_of_adoption',
    'attendance':'time_created',
    'numPeople':'time_created',
    'numAnimator':'time_created',
    'listPeople':'time_created',
    'listAnimator':'time_created',
    'listVideoScreened':'screening_date',
    'numVideoScreened':'screening_date',
    'listVideoProduced':'video_production_end_date',
    'numVideoProduced':'video_production_end_date',
    'list':'self',
    'listGroup':'time_created'
}


categoryDictionary={
    'geographies':['country','state','district','block','village'],
    'partitionCumValues':{'listAnimator':'animator','listVideoScreened':'video','listVideoProduced':'video','listPeople':'person','listGroup':'persongroup','numScreening':'numScreening'}
}

groupbyDictionary={
    'partner':'id',
    'country':'id',
    'state':'id',
    'district':'id',
    'block':'id',
    'village':'id',
    'animator':'animator_id',
    'person':'id',
    'persongroup':'id',
    'video':'video_id',
    'language':'id',
    'sector':'id',
    'practice':'id',
    'topic':'id',
    'numScreening':False,
    'numAdoption':False,
    'attendance':False,
    'numPeople':False,
    'numAnimator':False,
    'listPeople':'id',
    'listAnimator':'animator_id',
    'numVideoScreened':False,
    'numVideoProduced':False,
    'list':'self',
    'listVideoProduced':'video_id',
    'listVideoScreened':'video_id',
    'listGroup':'id'
}

selectDictionary={
    'partner':{'id':False,'partner_name':True},
    'country':{'id':False,'country_name':True},
    'state':{'id':False,'state_name':True},
    'district':{'id':False,'district_name':True},
    'block':{'id':False,'block_name':True},
    'village':{'id':False,'village_name':True},
    'animator':{'animator_id':False,'animator_name':True,'gender':False},
    'person':{'id':False,'person_name':True,'gender':True},
    'persongroup':{'id':False,'group_name':True},
    'video':{'id':False,'title':True},
    'language':{'id':False,'language_name':True},
    'sector':{'id':False,'name':True},
    'practice':{'id':False,'practice_name':True},
    'topic':{'id':False,'name':True},
    'numScreening':{'count(screening_id)':True,'count(distinct screening_id)':False},
    'numAdoption':{'count(person_id)':True,'count(distinct person_id)':True},
    'attendance':{'count(pma_id)':True,'count(distinct pma_id)':False},
    'numPeople':{'count(id)':True,'count(distinct id)':False},
    'numAnimator':{'count(id)':True,'count(distinct id)':False},
    'listPeople':{'person_name':True,'gender':False},
    'listAnimator':{'animator_name':True,'gender':False},
    'numVideoScreened':{'count(video_id)':True,'count(distinct id)':False},
    'numVideoProduced':{'count(id)':True,'count(distinct id)':False},
    'list':'self',
    'listVideoProduced':{'id':False,'title':True},
    'listVideoScreened':{'id':False,'video_title':True},
    'listGroup':{'id':False,'group_name':True}
}
