import datetime

MODEL_TYPES_DIRECT = 0
MODEL_TYPES_TAX_BASED = 1
MODEL_TYPES_SLAB_BASED = 2
MODEL_TYPES_DAILY_PAY = 3

ROLE_CHOICE_ADMIN = 1
ROLE_CHOICE_AGGREGATOR = 2
ROLE_CHOICE_TESTING = 3
ROLE_CHOICE_DEMO=4

DISCOUNT_CRITERIA_VOLUME = 0
DISCOUNT_CRITERIA_AMOUNT = 1

INCORRECT_FARMER_PHONE_MODEL_APPLY_DATE = datetime.datetime.strptime("2017-11-15", "%Y-%m-%d")
